### ISSUE TITLE
Create a document that lists and explains the features the app will have. 

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#17]

**Comment by leoschuster** [comment]
Status for standup: I am planning on working on this issue this week. I will create a document that will list and explain the features the app will have.

**Comment by jkr32** [comment]
[AppFeatures.pages.pdf](https://github.com/CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017/files/788620/AppFeatures.pages.pdf)

**Comment by DKlesel** [comment]
<img width="425" alt="screen shot 2017-02-21 at 3 14 00 pm" src="https://cloud.githubusercontent.com/assets/25308601/23185293/9234787e-f848-11e6-81d6-6410a7d81d13.png">

**Comment by DKlesel** [comment]
I worked on this for about 1 hour during Physics class today. I will work on it some more later on, but I am getting the hang of it.

**Comment by drlehr** [comment]
So Leo was going to work on this;  but  John moved it from BackLog to Done?
