### ISSUE TITLE
Design the menu interface and what it will show when opening the app etc

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#21]

**Comment by leoschuster** [comment]
Status for standup: I am planning on working this issue this week. I will hand-draw the menu interface and maybe transfer it to a Photoshop file. Completing this issue will allow us to code what we want our app to look like.

**Comment by DKlesel** [comment]
I've started working on this in AS. It involves a lot of XML coding. There is a steep learning curve. We might want to have a few of us get together and work on this together after we have done a bit of practice with it.

**Comment by DKlesel** [comment]
<img width="425" alt="screen shot 2017-02-21 at 3 14 00 pm" src="https://cloud.githubusercontent.com/assets/25308601/23185343/cca9c248-f848-11e6-8d32-228caba4e8c9.png">

I worked on this for about 1 hour during Physics class today. I will work on it some more later on, but I am getting the hang of it.

**Comment by DKlesel** [comment]
<img width="407" alt="screen shot 2017-02-21 at 3 42 07 pm" src="https://cloud.githubusercontent.com/assets/25308601/23186332/5f05bfc2-f84c-11e6-9a63-af24ebe7e192.png">

The text hint goes away when you enter text and each text box only accepts floating point numbers.

**Comment by DKlesel** [comment]
I assigned Nick and Duncan on this just because I think I remember you guys talking about the GUI in class. Anyways, we don't have to have all the specific code for this. Just a layout and design kinda thing. We can come up with some easily implemented ideas for page layouts and then in the next sprint we can do the code for it. 

Here's a cool interface that I found but I don't know how to implement it:
https://github.com/jpardogo/PagerSlidingTabStrip

**Comment by dms187** [comment]
We dont have the coding ready for the GUI, the learning curve on the actual creation of it being the main cause for me personally. Given the suggestion to create a visual map for what the most basic version of the system could look like, I drafted this.
![rough gui](https://cloud.githubusercontent.com/assets/25291747/23446956/12aeca6c-fe0d-11e6-989b-56fc223b0e6c.png)
