### ISSUE TITLE
Parent Calculator class

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#28]

**Comment by DKlesel** [comment]
I have worked up a working version of what the calculator class might look like. So far I am not quite sure how to work with inheritence a whole lot in Java. I was eventually wanting to implement the methods for calculating the chemicals as static classes that are subclasses of the superclass Calculator. However, for since I'm not sure how to do that yet I have just made those methods of the Calculator class instead. This took me 3 hours to complete.

**Comment by CodySpradling** [comment]
Changed class to take into consideration the changes to Chlorine.java and pH.java.
Fleshed out remaining calc functions.
