### ISSUE TITLE
Chlorine class

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#30]

**Comment by DKlesel** [comment]
Since it is only 20 minutes to finish line I'll go ahead and do this Cody.

**Comment by DKlesel** [comment]
I did what I could in the time remaining. It will need some edits. I would have started on this much earlier and made it much better if I knew you didn't have time to do it @CodySpradling.

**Comment by CodySpradling** [comment]
Finished class, to include the fact that it needs to take into consideration the three different possible chemicals.
