### ISSUE TITLE
Download and install android studio

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#8]

**Comment by leoschuster** [comment]
Android Studio download success. It took me 20 minutes to get it all running.

**Comment by DKlesel** [comment]
I have downloaded and installed Android studio on my machine. I also installed visual studio's cross platform development tools for c++.

**Comment by jkr32** [comment]
I have downloaded and installed Android studio on my Mac, took me about 15 minutes to get it all set up.
